#!/usr/bin/env python3
"""Render CATALOG.md from the hook modules' own metadata. Run with this file's directory on
PYTHONPATH (see `run`). CI regenerates and diffs against the committed file to catch staleness:
    python3 gen_catalog.py > /tmp/CATALOG.md && diff /tmp/CATALOG.md CATALOG.md
"""
from __future__ import annotations

import sys

from catalog import CATALOG


def render() -> str:
    lines = [
        "<!-- Generated by gen_catalog.py from the hook modules' own metadata. Do not edit. -->",
        "",   # prettier puts a blank line after a leading HTML comment
        "# Hook catalog",
        "",
        "Register a hook in a consumer by name, one line per hook, in `.claude/settings.json`",
        "and `.codex/hooks.json`, by absolute path. Claude Code: "
        "`$CLAUDE_PROJECT_DIR/.dpe-agent-config/hooks/agent/run <name>`; Codex: "
        "`bash \"$(git rev-parse --show-toplevel)/.dpe-agent-config/hooks/agent/run\" <name>`. "
        "A relative path resolves against the session's working directory, and a launcher it "
        "cannot find exits 127, which does not block. Not listed = not",
        "running.",
        "`MANDATORY` hooks must be registered on their event in both files (`verification.sh lint`",
        "enforces this); optional hooks are the consumer's choice.",
        "",
    ]
    lines.extend(_table())
    lines.append("")
    return "\n".join(lines)


def _table() -> list[str]:
    """The catalog table, with cells padded the way prettier formats markdown tables.

    Consumers run prettier across their whole tree and this file lands in it. Emitting the
    padding here is what lets the file be prettier-clean without excluding it -- and an excluded
    file is one their formatter would rewrite, which breaks `drift` against CHECKSUM.
    """
    header = ["Name", "Event", "Mandatory", "Description"]
    rows = [
        [f"`{e.name}`", f"`{e.event}`", "yes" if e.mandatory else "no", e.description]
        for e in sorted(CATALOG.values(), key=lambda e: e.name)
    ]
    # Prettier pads every cell to the widest in its column; the separator matches that width,
    # with a minimum of three dashes.
    widths = [max(len(r[i]) for r in [header, *rows]) for i in range(len(header))]
    def row(cells: list[str]) -> str:
        return "| " + " | ".join(c.ljust(w) for c, w in zip(cells, widths)) + " |"
    return [
        row(header),
        "| " + " | ".join("-" * max(w, 3) for w in widths) + " |",
        *(row(r) for r in rows),
    ]


if __name__ == "__main__":
    sys.stdout.write(render())
